BA-34-39-53-54-55-57: crud for pets endpoints and Allure Report
fnfldx/automationteststore pull request #26
Opened 2024-06-26 14:26 UTC by fnfldx

2024-07-04 07:11 UTC, Fishgame1 requested changes
Module names should be like:
api-test-pet-store

2024-07-04 09:13 UTC, ilku12 approved these changes

2024-07-04 11:40 UTC, Fishgame1 requested changes

2024-07-08 07:45 UTC, jakub-krzysiek approved these changes
@fnfldx Approved :) Can we make a quick call to discuss Allure integration between API and Java automated tests at some point?

2024-07-26 09:36 UTC, fnfldx commented on apitestpetstore/src/main/java/clients/PetClient.java
> +    private static final String PET_URL = BASE_URL + "/pet/";
I added the ``Routes`` class, where all endpoints are properly parameterized 
```java
package endpoints;

import static clients.BaseClient.BASE_URL;

public class Routes {
    //Pet
    public static final String PET_URL = BASE_URL + "/pet";
    public static final String PET_ADD = PET_URL;
    public static final String PET_UPDATE = PET_URL;
    public static final String PET_DELETE = PET_URL + "/{petId}";
    public static final String PET_UPDATE_BY_FORM = PET_URL + "/{petId}";
    public static final String PET_FIND_BY_ID = PET_URL + "/{petId}";
    public static final String PET_FIND_BY_STATUS = PET_URL + "/findByStatus";
    public static final String PET_UPLOAD_IMAGE = PET_URL + "/{petId}/uploadImage";
}
```
Przykład użycia w klasie ``PetClient`` - calling the ``.pathParam("petId", petId)`` method which will properly pass the ``petId`` to the url

```java 
    public Response deletePet(final long petId) {
        return RestAssured.given()
                    .pathParam("petId", petId)
                .when()
                    .delete(Routes.PET_DELETE);
    }
```

2024-07-26 10:41 UTC, Fishgame1 approved these changes

2024-07-26 10:42 UTC, merged